version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://json-server:3001

  json-server:
    image: node:14
    working_dir: /app
    volumes:
      - ./data:/app/data  # Maps the 'data' directory in your project to '/app/data' in the container
    command: npx json-server --watch data/todos.json --port 3001
    ports:
      - "3001:3001"
